bind pub - !do pub:do
set tekemiset {
"Pane"
"Lähe panee"
"KVG: http://bit.ly/1qf4Ncj"
"Tee jotain sellaista mitä sinun ei odoteta tekevän"
"Kysy kaverilta"
"Ehdota itse jotain"
"Lue jotain"
"Mene baariin"
"Lähde ryyppäämään"
"Mene uimaan"
"Mene saunaan"
"Meditoi"
"Murise"
"Laula"
"Käy hakemassa pikaruokaa"
"Nukkuisit joskus"
"Ota torkut"
"Mene kerjäämään rahaa"
"Mieti saatana itte"
"Etsi uutta musiikkia (Rekkaa www.last.fm)"
"Selaile koneessasi olevia tiedostoja, jos vaikka löytyisi jotain kivaa"
"Mene uimaan"
"Riko tavaroita"
"Hanki kaveri/kavereita"
"Ryhdy jehovantodistajaksi"
"Tee samaa mitä teit eilen"
"Jatka samaa mitä teet nytkin?"
"Halaa tyynyä. Forever alone"
"Palvo Saatanaa"
"Tee pahojasi"
"Katso animea"
"Katso leffa"
"Mene nukkumaan"
"Käy kävelyllä"
"Virkkaa"
"Pelaa jotain peliä"
"Lue kirjaa"
"Kirjoita"
"Käy kaverilla"
"Käy kaupungilla"
"Käy ostoksilla"
"Juo viinaa"
"Säästä rahaa"
"Tee hyvä teko"
"Tee itsellesi nettisivut, jos sinulla ei sellaisia vielä ole"
"Soita kitaraa, pianoa, tai jotain muuta soitinta"
"Tee musiikkia"
"Musisoi"
"Soita kaverillesi ja pyydä kylään"
"Soita kaverillesi ja kysy pääseekö käymään ja tehkää jotain kivaa"
"Soita kaverillesi ja pitäkää tyttöjen/ukkojen ilta"
"Lähde ryyppäämään. Heti"
"Käy paskalla"
"Lue vitsejä. !vitsi"
"Runkkaa"
"Katso pornoa"
"Juo kaljaa"
"Hali kaveria tai nallea. Nyt."
"Pyydä äiti kylään"
"Pyydä isä käymään"
"Lähde isän kanssa kalalle"
"Lähde kaverin kanssa kalalle"
"Lähde kylille"
"Lähde festareille tai keikalle. Tsekkaa onko livemusaa kaupungilla"
"Pyydä kaveri kylään"
"Leiki lemmikkisi kanssa"
"Irkkaa"
"Katso telkkaria"
"Katso jotain sarjaa"
"NO IRKKAA"
"Käy happihyppelyllä"
"Käy ajelulla"
"Jumppaa"
"Koodaa, jos et osaa: opettele. On olemassa codeacademya ja treehousea siihenkin tarkoitukseen"
"Tee nettisivuja, jos et osaa: opettele"
"Bloggaa Pulinaan http://www.pulina.fi/blogi"
"Bloggaa. Jos ei ole blogia, tee sellainen"
"Kuuntele musiikkia ja surffaa netissä (stumbleupon on hyvä paikka randomsurffaukseen: http://www.stumbleupon.com)"
"http://www.ircquotes.net/"
"No kysy vaikka rollelta"
"Kysy sopalta"
"Lue uutisia: http://www.ampparit.com/ "
"Lue iltalehteä: http://www.iltalehti.fi "
"Nuku vähän"
"Juo limsaa. Jos ei ole: osta"
"Pelaa, jos ei ole peliä hanki tai kysy muilta"
"Katso kelloa. Jos se on liikaa, mene nukkumaan"
"Hmm... keksi itte"
"Opiskele jotain hyödyllistä"
"Opettele uusi taito"
"Laske matematiikkaa"
"Asenna linux"
"Käy tekemässä heräteostoksia"
"Tee samaa mitä nytkin"
"Asenna Linux"
"Tee jotain uutta"
"Lepäile"
"Ota rennosti"
"Minäkö se aina joudun keksimään SULLE tekemistä? Mitä vittua? Keksi välillä ihan itte! Ei voi olla niin tylsää. Saatana"
"Onpa sulla huono mielikuvitus"
"Kirjoita satu"
"Kerro muille irkkaajille vitsi. NYT"
"Tsekkaa mitä muuta kivaa minä voin tehdä hyväksesi: http://pulina.fi/komennot"
"Random-irkkikuvia: http://peikko.us/pics"
"IRC-linkkejä: http://peikko.us/linkit"
"Etkö muka oikeasti keksi mitään tekemistä? nyt vittu oikeesti. Mahtaa olla tylsä elämä"
"Tee jotain uutta"
"Repäise ja lähde vaikka maailmanympärimatkalle"
"Mene paskalle ja jatka sieltä irkkaamista"
"Ainako pitäis keksiä.."
"!do !do !do !do !do !do !do !do !do !do !do !do ?do"
"do re mi fa sol.."
"do or don't do"
"Mene ja tiedä"
"Keksi tekemistä ittelles"
"Keksi tekemistä muille"
"Auta mummo kadun yli"
"Soita mummolle"
"Soita äidille"
"Soita isälle"
"Soita tädille"
"Soita sedälle"
"Soita papalle"
"Lähde ukin kanssa ryyppäämään"
"Juo mummon rahat"
"Neulo"
"Tee lapsia"
} 

proc pub:do {nick host hand chan $tekemiset} {
  global tekemiset
    puthelp "PRIVMSG $chan :[lindex $tekemiset [rand [llength $tekemiset]]]."
}

putlog "Script loaded: \002Keksi 1.0\002"
